### ISSUE TITLE
Incorrect calculation in 1.12 version when using the Gelu focus node.

### ISSUE THREAD

**Issue by zereth7** [gritemordle/ASPlanner#2]
If you choose the Gelu focus node in the 1.12 version then the planner seems to incorrectly include the +2% more perk effect nodes that are on the path to each gem slot node.

have not done too extensive testing, but i believe its limited to only them and working correctly otherwise.
(only tested in the 1.12 version, not sure if others are affected at all)

**Comment by gritemordle** [comment]
Thanks for catching that! The fix should be in now.
